function createfigure(n1, YMatrix1, x_cont1, YMatrix2)
%CREATEFIGURE(N1, YMATRIX1, X_CONT1, YMATRIX2)
%  N1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X_CONT1:  vector of x data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 16-Oct-2016 15:50:35

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
axis([80,1020,-.2,max(max(YMatrix1))+2.5]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(n1,YMatrix1,'Marker','o','LineStyle','none');
set(plot1(1),'DisplayName','Running time for Householder transformation',...
    'MarkerFaceColor',[0.850980401039124 0.325490206480026 0.0980392172932625],...
    'MarkerEdgeColor','none');
set(plot1(2),'DisplayName','Running time for Givens rotation',...
    'MarkerFaceColor',[0 0.447058826684952 0.74117648601532],...
    'Color',[1 1 1]);

% Create multiple lines using matrix input to plot
plot2 = plot(x_cont1,YMatrix2);
set(plot2(1),'DisplayName','Best fit for Householder transformation (n^3)',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);
set(plot2(2),'DisplayName','Best fit for Givens rotation (n^3)',...
    'Color',[0 0.447058826684952 0.74117648601532]);

% Create xlabel
xlabel('m = m of matrix mxn (n=m/2)');

% Create title
title({'Running time of Householder transformation vs Givens rotation'});

% Create ylabel
ylabel('t = running time (s)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[80 1020]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.5 12]);
box(axes1,'on');
% Create legend
legend(axes1,'show');

